name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      statuses: read
      security-events: write
    steps:
      - uses: actions/checkout@master
      - name: Generate Sarif File
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --severity-threshold=critical
      - name: Upload Sarif File to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
      - name: Monitor vulnerabilities with Snyk
        uses: snyk/actions/node@master
        continue-on-error: true # Don't break CI for now
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --fail-on=upgradable --severity-threshold=critical
          command: monitor